apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: podinfo
  namespace: test-app
spec:
  healthChecks:
  - kind: Deployment
    name: podinfo
    namespace: test-app
  interval: 1m0s
  path: ./kustomize
  prune: true
  sourceRef:
    kind: GitRepository
    name: podinfo
  timeout: 2m0s
  validation: client
